setup:
  device_number: "0"
  seed: 42
  output_dir: "saved_models"
  experiment_name: "finetune_test"

model:
  name_or_path: "PY007/TinyLlama-1.1B-Chat-v0.2"


data:
  rawdata_path: "data/rawdata/evidence_1.csv"