device_num : 0

model_name : "tiny_LLaMA_1b"
name : "tinyllama_1b"
out_dir : Path("out") / name

# Hyperparameters
num_of_devices : 8
global_batch_size : 512
learning_rate : 4e-4
micro_batch_size : 8
max_step : 715256 * 2
warmup_steps : 2000
log_step_interval : 10
eval_iters : 100
save_step_interval : 5000
eval_step_interval : 5000


weight_decay : 1e-1
beta1 : 0.9
beta2 : 0.95
grad_clip : 1.0
decay_lr : True
min_lr : 4e-5